version: '3.8'

services:
  php:
    build: .
    ports:
      - "8010:80"
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    volumes:
      # 1) Monte tout le projet racine dans /var/www
      - ./:/var/www
      # 2) Monte uniquement le dossier public dans /var/www/html (DocumentRoot Apache)
      - ./public:/var/www/html

  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
    env_file:
      - .env

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
