version: '3.8'

services:
  php:
    image: testphp.azurecr.io/php-app:latest
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    volumes:
      - ./public:/var/www/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
